include: package:flutter_lints/flutter.yaml

# 🚀 ELON MODE V2: RE-ENABLED CRITICAL RULES
# Date: December 16, 2025
# Goal: 10/10 Code Quality Score

analyzer:
  errors:
    # ✅ RE-ENABLED: Critical errors that must be fixed
    deprecated_member_use: warning
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    undefined_getter: error
    
    # 🟡 WARNINGS: Should fix but not blocking
    unused_element: warning
    override_on_non_overriding_member: warning
    body_might_complete_normally_nullable: warning
    unnecessary_null_comparison: warning
    unnecessary_cast: warning
    invalid_null_aware_operator: warning
    unnecessary_non_null_assertion: warning
    ambiguous_import: warning
    invalid_constant: warning
    unused_field: warning
    unreachable_switch_default: warning
    non_constant_list_element: warning
    const_with_non_const: warning
    dead_null_aware_expression: warning
    unused_shown_name: warning
    deprecated_member_use_from_same_package: warning
    unnecessary_import: warning
    
  exclude:
    - build/**
    - ios/**
    - android/**
    - web/**
    - "**.g.dart"
    - "**.freezed.dart"
    - "scripts/**"
    - "archive/**"
    - "_archive*/**"
    - "_ARCHIVED*/**"
    - "test/**"
    - "_flutter_scripts/**"

linter:
  rules:
    # ✅ RE-ENABLED: Critical code quality rules
    avoid_print: true
    prefer_final_fields: true
    use_rethrow_when_possible: true
    
    # 🟡 TEMPORARILY DISABLED: Too many occurrences, fix in batches
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    use_super_parameters: false
    
    # ✅ RE-ENABLED: Code quality rules
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    
    # ✅ RE-ENABLED: Best practices
    prefer_is_empty: true
    prefer_if_null_operators: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_to_list_in_spreads: true
    unnecessary_brace_in_string_interps: true
    unnecessary_string_interpolations: true
    unnecessary_const: true
    unnecessary_null_in_if_null_operators: true
    
    # 🟡 TEMPORARILY DISABLED: Fix in next phase
    curly_braces_in_flow_control_structures: false
    dangling_library_doc_comments: false
    camel_case_types: false
    library_private_types_in_public_api: false
    avoid_renaming_method_parameters: false
    use_full_hex_values_for_flutter_colors: false
    constant_identifier_names: false
    prefer_adjacent_string_concatenation: false
    non_constant_identifier_names: false
    depend_on_referenced_packages: false
    type_literal_in_constant_pattern: false
    unrelated_type_equality_checks: false
    library_prefixes: false
    file_names: false
    deprecated_member_use_from_same_package: false
    avoid_web_libraries_in_flutter: false
    no_leading_underscores_for_local_identifiers: false
