workflows:
  ios-debug:
    name: iOS Debug Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # iOS signing (will fail gracefully if missing)
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_API_KEY_BASE64: $APP_STORE_CONNECT_API_KEY_BASE64
        IOS_DISTRIBUTION_CERTIFICATE_BASE64: $IOS_DISTRIBUTION_CERTIFICATE_BASE64
        IOS_DISTRIBUTION_CERTIFICATE_PASSWORD: $IOS_DISTRIBUTION_CERTIFICATE_PASSWORD
        IOS_PROVISIONING_PROFILE_BASE64: $IOS_PROVISIONING_PROFILE_BASE64
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        
        # Supabase
        SUPABASE_URL: "https://mogjjvscxjwvhtpkrlqr.supabase.co"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZ2pqdnNjeGp3dmh0cGtybHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTk1ODAsImV4cCI6MjA3MzQ5NTU4MH0.u1urXd3uiT0fuqWlJ1Nhp7uJhgdiyOdLSdSWJWczHoQ"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Environment Check
        script: |
          echo "🔍 ENVIRONMENT DEBUG:"
          echo "  macOS: $(sw_vers -productVersion)"
          echo "  Xcode: $(xcodebuild -version | head -1)"
          echo "  Flutter: $(flutter --version | head -1)"
          echo "  Dart: $(dart --version)"
          echo "  CocoaPods: $(pod --version)"
          echo "  Ruby: $(ruby --version)"
          echo "  Git commit: $(git rev-parse --short HEAD)"
          
          echo "🔐 SIGNING VARIABLES:"
          echo "  API_KEY_ID: ${APP_STORE_CONNECT_API_KEY_ID:0:10}..."
          echo "  APPLE_TEAM_ID: ${APPLE_TEAM_ID:0:5}..."
          if [ -z "$APP_STORE_CONNECT_API_KEY_ID" ]; then
            echo "  ⚠️  GitHub Secrets not configured (continuing anyway)"
          else
            echo "  ✅ GitHub Secrets accessible"
          fi

      - name: Project Structure Check
        script: |
          echo "📁 PROJECT STRUCTURE:"
          echo "  Root files:"
          ls -la | head -10
          echo "  iOS folder:"
          ls -la ios/ | head -10
          echo "  pubspec.yaml exists: $(test -f pubspec.yaml && echo 'YES' || echo 'NO')"
          echo "  ios/Podfile exists: $(test -f ios/Podfile && echo 'YES' || echo 'NO')"

      - name: Flutter Dependencies
        script: |
          echo "📦 FLUTTER DEPENDENCIES:"
          flutter --version
          flutter doctor --verbose
          flutter pub get
          
          echo "🔍 KEY PLUGINS:"
          flutter pub deps --no-dev | grep -E "(camera|google_maps|geolocator|permission)" || echo "No problematic plugins found"

      - name: iOS Configuration Generation
        script: |
          echo "🔨 GENERATING iOS CONFIG:"
          flutter packages pub get
          cd ios
          
          echo "📋 BEFORE BUILD:"
          echo "  Generated.xcconfig exists: $(test -f Flutter/Generated.xcconfig && echo 'YES' || echo 'NO')"
          
          cd ..
          echo "🏗️ Generating iOS build config..."
          # Try to generate iOS configuration without full build
          flutter packages pub run build_runner build || echo "No code generation needed"
          
          cd ios
          echo "📋 AFTER PREPARATION:"
          echo "  Generated.xcconfig exists: $(test -f Flutter/Generated.xcconfig && echo 'YES' || echo 'NO')"
          if [ -f "Flutter/Generated.xcconfig" ]; then
            echo "  Generated.xcconfig contents:"
            cat Flutter/Generated.xcconfig
          fi

      - name: Pod Install Debug
        script: |
          echo "🚀 POD INSTALL DEBUG:"
          cd ios
          
          echo "📊 PRE-INSTALL STATE:"
          echo "  Current directory: $(pwd)"
          echo "  Podfile exists: $(test -f Podfile && echo 'YES' || echo 'NO')"
          echo "  Generated.xcconfig: $(test -f Flutter/Generated.xcconfig && echo 'YES' || echo 'NO')"
          echo "  Pods folder exists: $(test -d Pods && echo 'YES' || echo 'NO')"
          echo "  Podfile.lock exists: $(test -f Podfile.lock && echo 'YES' || echo 'NO')"
          
          echo "📋 PODFILE CONTENT:"
          cat Podfile
          
          echo "🧹 CLEANING:"
          rm -rf Pods/ Podfile.lock .symlinks/ || echo "Nothing to clean"
          
          echo "🔍 FLUTTER ROOT CHECK:"
          if [ ! -f "Flutter/Generated.xcconfig" ]; then
            echo "❌ Generated.xcconfig missing! Creating minimal version..."
            mkdir -p Flutter
            echo "FLUTTER_ROOT=/Users/builder/programs/flutter" > Flutter/Generated.xcconfig
            echo "FLUTTER_APPLICATION_PATH=$(pwd)/.." >> Flutter/Generated.xcconfig
            echo "COCOAPODS_PARALLEL_CODE_SIGN=true" >> Flutter/Generated.xcconfig
            echo "FLUTTER_TARGET=lib/main.dart" >> Flutter/Generated.xcconfig
            echo "FLUTTER_BUILD_DIR=build" >> Flutter/Generated.xcconfig
            echo "SYMROOT=\${SOURCE_ROOT}/../build/ios" >> Flutter/Generated.xcconfig
            echo "OTHER_LDFLAGS=\$(inherited) -framework Flutter" >> Flutter/Generated.xcconfig
            echo "FLUTTER_FRAMEWORK_DIR=/Users/builder/programs/flutter/bin/cache/artifacts/engine/ios" >> Flutter/Generated.xcconfig
            echo "FLUTTER_BUILD_NAME=1.0.1" >> Flutter/Generated.xcconfig
            echo "FLUTTER_BUILD_NUMBER=5" >> Flutter/Generated.xcconfig
            echo "DART_OBFUSCATION=false" >> Flutter/Generated.xcconfig
            echo "TRACK_WIDGET_CREATION=false" >> Flutter/Generated.xcconfig
            echo "TREE_SHAKE_ICONS=false" >> Flutter/Generated.xcconfig
            echo "PACKAGE_CONFIG=.dart_tool/package_config.json" >> Flutter/Generated.xcconfig
            echo "✅ Minimal Generated.xcconfig created"
          fi
          
          echo "🚀 POD INSTALL ATTEMPT:"
          set -x
          pod install --verbose 2>&1 | tee pod_install_full.log
          POD_EXIT_CODE=$?
          set +x
          
          echo "📊 POD INSTALL RESULT:"
          echo "  Exit code: $POD_EXIT_CODE"
          echo "  Pods created: $(test -d Pods && echo 'YES' || echo 'NO')"
          echo "  Podfile.lock created: $(test -f Podfile.lock && echo 'YES' || echo 'NO')"
          echo "  Workspace created: $(test -d Runner.xcworkspace && echo 'YES' || echo 'NO')"
          
          if [ $POD_EXIT_CODE -ne 0 ]; then
            echo "❌ POD INSTALL FAILED!"
            echo "📋 LAST 50 LINES OF LOG:"
            tail -50 pod_install_full.log
            echo "🔍 ERROR ANALYSIS:"
            grep -i "error\|failed\|exception" pod_install_full.log | tail -10
            exit 1
          else
            echo "✅ POD INSTALL SUCCESS!"
            echo "📋 INSTALLED PODS:"
            ls -la Pods/ | head -10
          fi

    artifacts:
      - ios/pod_install_full.log
      - ios/Podfile.lock
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - longsangsabo@gmail.com
        notify:
          success: true
          failure: true