import 'club_role.dart';

/// Club Permission Model
/// Represents user permissions within a club
class ClubPermission {
  final String id;
  final String clubId;
  final String userId;
  final ClubRole role;

  // Detailed permissions
  final bool canVerifyRank;
  final bool canInputScore;
  final bool canManageTables;
  final bool canViewReports;
  final bool canManageMembers;
  final bool canManagePermissions;

  // Metadata
  final String? grantedBy;
  final DateTime grantedAt;
  final DateTime updatedAt;

  const ClubPermission({
    required this.id,
    required this.clubId,
    required this.userId,
    required this.role,
    required this.canVerifyRank,
    required this.canInputScore,
    required this.canManageTables,
    required this.canViewReports,
    required this.canManageMembers,
    required this.canManagePermissions,
    this.grantedBy,
    required this.grantedAt,
    required this.updatedAt,
  });

  factory ClubPermission.fromJson(Map<String, dynamic> json) {
    return ClubPermission(
      id: json['id'] as String,
      clubId: json['club_id'] as String,
      userId: json['user_id'] as String,
      role: ClubRole.fromString(json['role'] as String),
      canVerifyRank: json['can_verify_rank'] as bool? ?? false,
      canInputScore: json['can_input_score'] as bool? ?? false,
      canManageTables: json['can_manage_tables'] as bool? ?? false,
      canViewReports: json['can_view_reports'] as bool? ?? false,
      canManageMembers: json['can_manage_members'] as bool? ?? false,
      canManagePermissions: json['can_manage_permissions'] as bool? ?? false,
      grantedBy: json['granted_by'] as String?,
      grantedAt: DateTime.parse(json['granted_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'club_id': clubId,
      'user_id': userId,
      'role': role.value,
      'can_verify_rank': canVerifyRank,
      'can_input_score': canInputScore,
      'can_manage_tables': canManageTables,
      'can_view_reports': canViewReports,
      'can_manage_members': canManageMembers,
      'can_manage_permissions': canManagePermissions,
      'granted_by': grantedBy?.isEmpty == true
          ? null
          : grantedBy, // Fix: convert empty string to null
      'granted_at': grantedAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Get default permissions for a role
  factory ClubPermission.defaultForRole({
    required String clubId,
    required String userId,
    required ClubRole role,
    String? grantedBy,
  }) {
    final now = DateTime.now();
    return ClubPermission(
      id: '', // Will be generated by DB
      clubId: clubId,
      userId: userId,
      role: role,
      canVerifyRank: role.canVerifyRank,
      canInputScore: role.canInputScore,
      canManageTables: role.canManageTables,
      canViewReports: role.canViewReports,
      canManageMembers: role.canManageMembers,
      canManagePermissions: role.canManagePermissions,
      grantedBy: grantedBy,
      grantedAt: now,
      updatedAt: now,
    );
  }

  ClubPermission copyWith({
    String? id,
    String? clubId,
    String? userId,
    ClubRole? role,
    bool? canVerifyRank,
    bool? canInputScore,
    bool? canManageTables,
    bool? canViewReports,
    bool? canManageMembers,
    bool? canManagePermissions,
    String? grantedBy,
    DateTime? grantedAt,
    DateTime? updatedAt,
  }) {
    return ClubPermission(
      id: id ?? this.id,
      clubId: clubId ?? this.clubId,
      userId: userId ?? this.userId,
      role: role ?? this.role,
      canVerifyRank: canVerifyRank ?? this.canVerifyRank,
      canInputScore: canInputScore ?? this.canInputScore,
      canManageTables: canManageTables ?? this.canManageTables,
      canViewReports: canViewReports ?? this.canViewReports,
      canManageMembers: canManageMembers ?? this.canManageMembers,
      canManagePermissions: canManagePermissions ?? this.canManagePermissions,
      grantedBy: grantedBy ?? this.grantedBy,
      grantedAt: grantedAt ?? this.grantedAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

/// Extended club member with role and permissions
class ClubMemberWithPermissions {
  final String id;
  final String clubId;
  final String userId;
  final String userName;
  final String? userAvatar;
  final String? userRank;
  final int? eloRating;
  final String? skillLevel;
  final ClubRole role;
  final DateTime joinedAt;

  // Optional: Detailed permissions if custom
  final ClubPermission? customPermissions;

  const ClubMemberWithPermissions({
    required this.id,
    required this.clubId,
    required this.userId,
    required this.userName,
    this.userAvatar,
    this.userRank,
    this.eloRating,
    this.skillLevel,
    required this.role,
    required this.joinedAt,
    this.customPermissions,
  });

  factory ClubMemberWithPermissions.fromJson(Map<String, dynamic> json) {
    return ClubMemberWithPermissions(
      id: json['id'] as String,
      clubId: json['club_id'] as String,
      userId: json['user_id'] as String,
      userName: json['user_name'] as String? ?? 'Unknown',
      userAvatar: json['user_avatar'] as String?,
      userRank: json['user_rank'] as String?,
      eloRating: json['elo_rating'] as int?,
      skillLevel: json['skill_level'] as String?,
      role: ClubRole.fromString(json['role'] as String? ?? 'member'),
      joinedAt: DateTime.parse(json['joined_at'] as String),
      customPermissions: json['permissions'] != null
          ? ClubPermission.fromJson(json['permissions'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Get effective permissions (custom or default)
  ClubPermission get effectivePermissions {
    return customPermissions ??
        ClubPermission.defaultForRole(
          clubId: clubId,
          userId: userId,
          role: role,
        );
  }

  bool get canVerifyRank => effectivePermissions.canVerifyRank;
  bool get canInputScore => effectivePermissions.canInputScore;
  bool get canManageTables => effectivePermissions.canManageTables;
  bool get canViewReports => effectivePermissions.canViewReports;
  bool get canManageMembers => effectivePermissions.canManageMembers;
  bool get canManagePermissions => effectivePermissions.canManagePermissions;
}
